### ISSUE TITLE
config.yml 各个参数可以提供更详细的说明么？

### ISSUE THREAD

**Issue by justincnn** [wooveep/chatserver-api#3]
比如：
openai:
  authtoken:
  orgid:

这里的是api 还是token？谢谢回复

**Comment by wooveep** [comment]
这项目就是只支持 OPENAI 的API的呢； authtoken 就是填写 API key， orgid 就是
https://platform.openai.com/account/org-settings 页面上的 Organization ID

justincnn ***@***.***>于2023年5月17日 周三16:54写道：
