### ISSUE TITLE
前端连后端出错，前端页面没有验证码弹出

### ISSUE THREAD

**Issue by cdssd** [wooveep/chatserver-api#5]
后台API docker 部署，正常启动：
[GIN-debug] POST   /admin/cdkeygen           --> chatserver-api/internal/handler/v1/admin.(*AdminHandler).AdminGenNewCDkey.func1 (9 handlers)
[GIN-debug] POST   /admin/cardcreate         --> chatserver-api/internal/handler/v1/admin.(*AdminHandler).AdminCreateGiftCard.func1 (9 handlers)
[GIN-debug] POST   /admin/cardupdate         --> chatserver-api/internal/handler/v1/admin.(*AdminHandler).AdminUpdateGiftCard.func1 (9 handlers)
2023-05-29 15:51:29.074 INFO    middleware/logger.go:34 New request start       {"appName": "chatserver-api", "request_id": "8fa124af1ddd41ef", "host": "127.0.0.1", "host": "127.0.0.1", "path": "/ping", "method": "GET", "body": ""}
2023-05-29 15:51:29.074 INFO    middleware/logger.go:45 New request end {"appName": "chatserver-api", "request_id": "8fa124af1ddd41ef", "host": "127.0.0.1", "path": "/ping", "cost": "317.083µs"}
[GIN] 2023/05/29 - 15:51:29 | 200 |     370.248µs |       127.0.0.1 | GET      "/ping"
2023-05-29 15:51:29.074 INFO    chatserver-api/server.go:62     server started success! port: :18080    {"appName": "chatserver-api"}

2023-05-29 15:52:48.675 INFO    middleware/logger.go:34 New request start       {"appName": "chatserver-api", "request_id": "669f75452d2948c7", "host": "172.16.10.31", "host": "172.16.10.31", "path": "/captcha", "method": "GET", "body": ""}

前台API docker 部署，正常启动：
2023/05/29 07:52:19 [notice] 1#1: using the "epoll" event method
2023/05/29 07:52:19 [notice] 1#1: nginx/1.23.4
2023/05/29 07:52:19 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2023/05/29 07:52:19 [notice] 1#1: OS: Linux 5.15.0-72-generic
2023/05/29 07:52:19 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/05/29 07:52:19 [notice] 1#1: start worker processes
2023/05/29 07:52:19 [notice] 1#1: start worker process 9
2023/05/29 07:52:19 [notice] 1#1: start worker process 10
2023/05/29 07:52:19 [notice] 1#1: start worker process 11
2023/05/29 07:52:19 [notice] 1#1: start worker process 12

问题：
1，打开前端页面注册，没有验证码输出，无法验证
2，后台控制台有相关错误输出：
![20230529160249](https://github.com/wooveep/chatserver-api/assets/116550571/898adf1d-0722-4691-86e4-7c515b8a9f97)

**Comment by wooveep** [comment]
您拉取一下最新的代码生成进行docker镜像，
或者直接拉取最新的 docker镜像呢
docker pull  wooveep/chatserver-web:latest 

docker pull  wooveep/chatserver-api:latest 
之前docker镜像忘记更新了。

**Comment by wooveep** [comment]
@cdssd

**Comment by cdssd** [comment]
2023-05-30 09:05:53.296 WARN    db/db.go:28     /code/src/internal/dao/query/user.go:114 failed to connect to `host=172.16.30.138 user=appuser database=chatgptapi`: failed to receive message (unknown message type: J)

**Comment by cdssd** [comment]
api还有报错，这个mysql是正常能连接的

**Comment by cdssd** [comment]
有没有缺省的管理员账号

**Comment by wooveep** [comment]
那个配置文件里面注释有误 后台需要postgresql 数据的呢。 
https://github.com/wooveep/chatserver-api#%E9%83%A8%E7%BD%B2%E5%AE%89%E8%A3%85%E5%B8%A6%E6%9C%89pgvector%E6%8F%92%E4%BB%B6%E7%9A%84postgresql

**Comment by cdssd** [comment]
需要postgresql 不是mysql是把，需要再config里面配置postgresql的信息不

**Comment by wooveep** [comment]
是的呢

**Comment by cdssd** [comment]
配置postgresql ，点击登录或者注册，api还是有报错：
2023-05-30 14:38:03.821 WARN    db/db.go:28     /code/src/internal/dao/query/user.go:114 错误: 关系 "public.user" 不存在 (SQLSTATE 42P01)

**Comment by cdssd** [comment]
用户注册成功后，无法正常聊天，发送按钮不能点击
![image](https://github.com/wooveep/chatserver-api/assets/116550571/dab408df-7814-45c2-a175-8c995c22e9c8)

**Comment by wooveep** [comment]
要先刷库 😓
https://github.com/wooveep/chatserver-api#%E5%8A%A0%E8%BD%BD%E9%A1%B9%E7%9B%AE%E6%89%80%E9%9C%80%E7%9A%84%E5%BA%93%E8%A1%A8

SQL 位于项目 目录 script/sql目录下的 init.sql 文件

cdssd ***@***.***>于2023年5月30日 周二16:20写道：

**Comment by cdssd** [comment]
数据库导入出错了

错误:  关系 "public.bill" 的 "amount" 字段不存在
COMMENT
CREATE TABLE
CREATE INDEX
CREATE SCHEMA
错误:  类型 "vector" 不存在
第6行 embedding vector NULL,
                ^
错误:  关系 "embed.documents" 不存在

**Comment by cdssd** [comment]
[GIN] 2023/05/31 - 09:43:48 | 400 |     890.723µs |    172.16.10.31 | POST     "/chat/chatting"，
聊天无响应

**Comment by wooveep** [comment]
postgresql需要开启pgvector插件哦 

部署安装带有pgvector插件的postgresql
可以参考 https://github.com/pgvector/pgvector#installation-notes 部分内容

**Comment by zannet** [comment]
> [GIN] 2023/05/31 - 09:43:48 | 400 | 890.723µs | 172.16.10.31 | POST "/chat/chatting"， 聊天无响应
同报这个错，@wooveep 大佬帮忙看下

**Comment by wooveep** [comment]
> > [GIN] 2023/05/31 - 09:43:48 | 400 | 890.723µs | 172.16.10.31 | POST "/chat/chatting"， 聊天无响应
> > 同报这个错，@wooveep 大佬帮忙看下

首先看下 前置条件否是都以满足。
部署redis服务
部署安装带有pgvector插件的postgresql
可以参考 https://github.com/pgvector/pgvector#installation-notes 部分内容

加载项目所需的库表
项目还在测试阶段，每次更新都可能会修改数据库结构，建议更新时先更新SQL 位于项目 目录 script/sql目录下的 init.sql 文件

确保配置文件中的 API 相关项正确填写。

openai:
  apitype:                                          #填写 “azure”或“openai” 默认为openai
  apiurl:                                       #当使用azure API 时需要填写API终结点地址
  apiversion: "2023-05-15"        #当使用azure API 时需要填写APIversion
  authtoken:                                  #填写 azure 密钥  或 openai API KEY 
  orgid:                                      #OPENAI页面的组织ID 如果使用azureAPI不需要填写
  proxymode: socks5      #如果为空则不使用代理(支持填写socks5或者http)
  proxyip:                          
  proxyport:

**Comment by wooveep** [comment]
```
INSERT INTO public.preset (id, preset_name, preset_content, max_token, model_name, logit_bias, temperature, top_p, presence, frequency, created_at, updated_at, with_embedding, deleted_at, is_del, classify, privilege, preset_tips, "extension") VALUES(1646361709138419712, '智能助手', 'You are ChatGPT, a large language model trained by OpenAI. Please strictly follow the rules below when answering the user''s questions.
Knowledge cutoff: 2021-09 
Current date: {{ current_date }}
Rules:\```
1.All answers are to be provided in Markdown format.
2.When you receive the instruction ''[cmd:continue]'', please continue answering questions directly from where you left off in the previous response. You do not need to explain the interruption in your response.
3. If the user''s language is Chinese, please answer the user''s questions in Chinese.
\```', 300, 'gpt-3.5-turbo', NULL, 0.2, 0.9, 0.3, 0.3, '2023-04-13 11:56:34.057', '2023-05-28 10:33:12.468', false, '0001-01-01 08:00:00.000', 0, NULL, 1, '我擅长根据问题生成具有创意的内容。
但对于刚刚发生的事情，以及未来发生的事情我无法回答。
比如我无法告诉今天的天气怎么样。
你可以问我：
“如何高效的阅读？”
“天空为什么是蓝色的？”', 1);
```
@cdssd  你这个应该也是 preset表为空。
