### ISSUE TITLE
preset数据表为空

### ISSUE THREAD

**Issue by zannet** [wooveep/chatserver-api#6]
大佬，能提供下preset表的数据么，preset列表为空，前端无法初始化聊天

**Comment by wooveep** [comment]
INSERT INTO public.preset (id, preset_name, preset_content, max_token, model_name, logit_bias, temperature, top_p, presence, frequency, created_at, updated_at, with_embedding, deleted_at, is_del, classify, privilege, preset_tips, "extension") VALUES(1646361709138419712, '智能助手', 'You are ChatGPT, a large language model trained by OpenAI. Please strictly follow the rules below when answering the user''s questions.
Knowledge cutoff: 2021-09 
Current date: {{ current_date }}
Rules:```
1.All answers are to be provided in Markdown format.
2.When you receive the instruction ''[cmd:continue]'', please continue answering questions directly from where you left off in the previous response. You do not need to explain the interruption in your response.
3. If the user''s language is Chinese, please answer the user''s questions in Chinese.
```', 300, 'gpt-3.5-turbo', NULL, 0.2, 0.9, 0.3, 0.3, '2023-04-13 11:56:34.057', '2023-05-28 10:33:12.468', false, '0001-01-01 08:00:00.000', 0, NULL, 1, '我擅长根据问题生成具有创意的内容。
但对于刚刚发生的事情，以及未来发生的事情我无法回答。
比如我无法告诉今天的天气怎么样。
你可以问我：
“如何高效的阅读？”
“天空为什么是蓝色的？”', 1);

**Comment by wooveep** [comment]
> 初始
最近一次更新忘记添加初始化SQL了

**Comment by zannet** [comment]
@wooveep 大佬，智能搜搜的Preset能提供不

**Comment by wooveep** [comment]
curl --location --request POST '[http://API服务IP+端口/preset/new](http://xn--apiip+-df4jg7fot3eot3b/preset/new)'
--header 'User-Agent: curl'
--header 'Content-Type: application/json'
--header 'Authorization: Bearer 获取token'
--header 'Accept: /'
--header 'Connection: keep-alive'
--data-raw '{
"preset_name": "智能搜搜test", // 自行修改
"preset_content": "角色设定内容。。。 Current date: {{ current_date }} ## Context: """ {{ context }} """", // 自行修改  
"max_token": 200,
"temperature": 0.4,
"top_p": 1,
"presence": 0.1,
"frequency": 0.1,
"preset_tips": "使用提示", // 自行修改
"extension": 2,
"privilege": 1
}'
content 中这个 部分不要改动就好了  Current date: {{ current_date }} ## Context: """ {{ context }} """  ，让gpt根据context段落内容回答。
