### ISSUE TITLE
大佬 ，部署好之后角色只有两个

### ISSUE THREAD

**Issue by wrhsd1** [wooveep/chatserver-api#7]
如图[](https://cgimg.cavpn.tk/uPic/2023-06-12-13-25/oItGfB.png)
https://cgimg.cavpn.tk/uPic/2023-06-12-13-25/oItGfB.png
配置里也添加了谷歌和腾讯的api 这是什么情况

**Comment by wrhsd1** [comment]
感谢大佬回复！
试了一下，获取token这里应该是哪个啊，提示
message":"invalid token, token contains an invalid number of segments"
另外使用谷歌搜索的话，应该怎么写呢？

**Comment by wooveep** [comment]
jwttoken 是通过login接口获取的；

使用谷歌搜索的话
根据context的内容回答用户用户问题  Current date: {{ current_date }}  ## Context: """ {{ context }} """  ，然后其他的自由发挥写一些别的限制就OK
