### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by zannet** [wooveep/chatserver-api#9]
当请求超时时，会引起panic，错误如下：

panic: close of closed channel

goroutine 47 [running]:
chatserver-api/internal/service.(*chatService).ChatStremResGenerate(0x0?, 0x0?, 0x0, {{0xc000047040, 0xd}, {0xc0004cb880, 0x6, 0x8}, 0x7d0, 0x0, ...}, ...)
        /root/chatserver-api/internal/service/chat.go:625 +0x6f2
chatserver-api/internal/handler/v1/chat.(*ChatHandler).ChatChatting.func1.1()
        /root/chatserver-api/internal/handler/v1/chat/chat.go:178 +0xc8
created by chatserver-api/internal/handler/v1/chat.(*ChatHandler).ChatChatting.func1
        /root/chatserver-api/internal/handler/v1/chat/chat.go:176 +0x7ae

**Comment by wooveep** [comment]
已经更新
